id: A18366B25
title: A Sādhana of Golden Mañjughoṣa
type: translation
pechas:
- I64CDA0CD
- I6CA24161
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 11:38:54.143387
  last_modified_at: 2023-01-04 11:38:54.143398
  collections:
  - Dilgo Khyentse Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I64CDA0CD/8B06: 12C3
  I6CA24161/42C5: 12C3
